const animalSymbols = [
    "Bat: fear, vampire, satan, soul-sucker, cave, nocturnal, swallow the light, suspicion, darkness",
    "Bear: hibernation, new life, resurrection, strength, power, size",
    "Birds: transition, freedom, liberty, flight, transport",
    "Buffalo: earth, bravery, freedom, kindness, strength, respect, gratitude, true to one's self, safety, power, durability",
    "Bull: majesty, virility, sovereignty, wealth, masculine power, connection to the gods",
    "Butterfly: transformation, significant change, death and rebirth, old self dying, new self emerging",
    "Cat: mystique, supernatural, witch, magical secrets, arcane knowledge, deity, goddess, balance, agility, magnetism, mourning, nine-lives",
    "Cow: earth, power, mother, nurturing, fertility, steadfastness, compassion, perception",
    "Coyote: trickster, miracle-worker, shape shifter, howling, moon, door to other world, messenger, evil, bad luck",
    "Crocodile: predator, connection to the gods, fierceness",
    "Crow: magic, mystery, higher perspective, flexibility, trickster, double-edged nature, manipulation",
    "Deer: majesty, woodland deities, profound change",
    "Dog: shapeshifter, man's best friend, guard, vigilant, faithful, wise, fidelity, female seduction",
    "Dolphin: new age, benevolence, intelligence, communication, womb, helpful, friend, spiritual guide, other-dimension, alien, pirate",
    "Dove: gentle nature, universal peace, innocence, purity, the soul, Holy Spirit, Holy Grail",
    "Duck: marital happiness, fidelity, wedding invitations, lucky, feasting, clairvoyance",
    "Eagle: feared scavenger, death, death-related deities, reconnection with one's spiritual path, embark on a spiritual journey, a reminder to listen to one's heart",
    "Elephant: large, powerful, battle, military might and triumph",
    "Falcon: ferocity, rising sun, image of gods, king, victory, rulership, overcomming, higher self, spiritual connections, hunting, war, higher vision, success, victory",
    "Fish: depths, underworld, secrecy, secret places, forbidden places, water, womb, wisdom, fisherman, wedding",
    "Fox: sly, cunning, deceitful, devil-like qualities, wealth, fertility, agriculture",
    "Frog: fairy tale, prince's curse, kiss, transformation, resurrection, amulet, charm, water, drum, thunder, rain, fertility",
    "Giraffe: elevation of the spirit, sincerity, kindness, softness, interior calm, spirit guide, reaching heights, self acceptance, self-love, proud appearance, uniqueness",
    "Goat: maintaining life, creating life, fertility, abundance, lust, vitality, creativity, virility",
    "Grasshopper: constantly on-the-move, take a leap of faith, good luck, good vibes, break confliction, make a decision",
    "Hawk: valiance, pride, courage, self-awareness, truth, perspective, intuition, inner wisdom, assessment",
    "Horse: beast of burden, powerhouse, strength, power, resiliency, stamina, wisdom, freedom, wildness, intellect, loyalty, nobility, divination, prophecy",
    "Hummingbird: optimism, speed, lightness, connection, playfulness, adaptability, don't take things so seriously!",
    "Jaguar: killer blow, all beast, guardian, nocturnal, night, moon goddess, occult, second-sight, prophecy, supernatural vision, temple",
    "Lamb: positivity, innocence, purity, spirituality, compliance, gentleness, spring, new hope, sacrifice, resurrection, halo",
    "Leopard: speed, ferocity, aggression, courage, activity",
    "Lion: sun, Leo, great star, Christ, halo, male energy, lioness, ferocity, protective, chariot",
    "Lizard: resurrection, rebirth, regeneration, regrowth, shedding skin, growth, survival, birth of a boy",
    "Longhorn: masculinity, tenacity, determination, strength, power, abundance, wealth",
    "Monkey: quick, keen wit, high observance, curiosity, devilish, fall of man, earthly desires, copycat",
    "Mouse: destroyer-protector, plague, soul leaving the body",
    "Peacock: magic, immortality, resurrection of Christ, eternal life, majesty, pride, vanity, self-assurance",
    "Phoenix: rise from ashes, rebirth, hope, renewal, progress, eternity, prosperity, happiness",
    "Owl: rare, spirituality, wisdom, patience, solitude, deep connection, intuitive knowledge, wide-eyes piercing through deceit, seeing beyond illusions",
    "Pig: dirt, greed, uncouthness, ignorance, gluttony, selfishness",
    "Rabbit: always on the move, alert, lust, sexual desire",
    "Ram: leading with horns, breakthrough, full speed, sacrifice, achievement, sun, creativity, virility",
    "Raven: mystery, mysterious, trickster, shape shifter, dark side, death, high intelligence, wisdom, cleverness",
    "Scarab: belonging to the god of the rising sun",
    "Scorpion: danger, venom, invocation, prepared to attack, sting, weapon unsheathed, brute aggression, pain",
    "Sheep: blindness, blind faith, follow the flock",
    "Snake: regeneration, renewal, female sexuality, agricultural fertility, underworld, temptation, forbidden fruit, malice, poison",
    "Spider: intricacy, webs, inspiration, fate, destiny, creator of possibilities",
    "Squirrel: abundance, fertility, new beginnings, good luck, enjoy the moment, stay busy during uncertainty, management",
    "Tiger: king of beasts, ferocity, earth, power, anger, strength, courage, determination, military prowess, protection, awareness, confidence, ward off malevolent spirits",
    "Turtle: slow-moving, sturdy, secrets, sacred symbols, four elements, four directions, map, world tree",
    "Unicorn: mystical, purity, grace, virginity, dreams, virtue, integrity, healing, freedom",
    "Wolf: sharp intelligence, self reliance, appetite for freedom, mysterious, intimidating, perseverance, stability, intuition, loyalty, success",
    "Whale: initiation, death, rebirth"
]