
const namesBritishFemales = [
    "Abigail", "Ada", "Adele", "Alexandra", "Alice", "Amber", "Amelia", "Amy", "Anna", "Annabelle", "Anne", "Aria", "Ariana", "Ariel", "Asher", "Ashley", "Audrey", "Aurora",
    "Ava", 
    "Beatrice", "Bella", "Bethany", "Bianca", "Bonnie", "Brianna", "Brooke", 
    "Camilla", "Carla", "Catherine", "Charlotte", "Chloe", "Clara", "Clementine", "Cleo", 
    "Daisy", "Dakota", "Dana", "Daniella", "Daphne", "Darcie", "Daria", "Davina", "Dawn", "Daya", "Divine", "Deborah", "Delilah", "Demi", "Destiny", "Diana", "Dixie", "Dollie", "Dora", "Dorothy", "Dottie",
    "Edith", "Eleanor", "Eliza", "Elizabeth", "Ella", "Ellie", "Elsie", "Emily", "Emma", "Erin", "Esme", "Ethel", "Eva", "Evelyn",
    "Evie", 
    "Faith", "Farah", "Faye", "Felicia", "Felicity", "Fern", "Fifi", "Flora", "Florence", "Flossie", "Flower", "Francesca", "Frederica", "Freya", "Frida", 
    "Georgia", "Georgina", "Gertrude","Gillian","Grace", 
    "Hallie", "Hannah", "Harper", "Harriet", "Hazel", "Heidi", "Helen", "Helena", "Hermione", "Holly", 
    "Imogen", "India", "Isabella", "Isla", "Ivy", 
    "Janice", "Jaqueline", "Jasmine", "Jennifer", "Jessica", "Joan", "Joanna", "Josephine", "Joy", "Judy", "Julia", "Juliet",
    "Kate", "Katherine", "Katie", "Kelly", "Kelsie", "Kirsty",
    "Lara", "Laura", "Lauren", "Layla", "Leah", "Lilly", "Lily", "Lucy", "Luna", "Lydia", 
    "Maisie", "Margaret", "Martha", "Mary", "Matilda", "Maya", "Megan", "Millie", "Molly", 
    "Nancy", "Naomi", "Natasha", "Niamh",
    "Olivia", "Ophelia", "Orla", 
    "Paige", "Patricia", "Paulina", "Peggy", "Phoebe", "Poppy", "Posy", "Prudence",
    "Rebecca", "Rosaline", "Rose", "Rosie", "Ruby", 
    "Sally", "Samantha", "Sandy", "Sarah", "Sophie", "Stephanie", "Stevie",
    "Tamara", "Teri", "Tess", "Trishia", "Trudy", 
    "Valentina", "Valerie", "Vanessa", "Venus", "Vera", "Veronica", "Victoria", "Vienna", "Viola", "Violet", "Virginia", "Vivienne",
    "Willow", "Winifred", "Winter"
];
const namesBritishMales = [
    "Aaron", "Abe", "Adam", "Adrian", "Albie", "Albert", "Alexander", "Alfie", "Alfred", "Andrew", "Angus", "Anthony", "Archie", "Arthur", "Asher", "Austin", 
    "Barney", "Ben", "Benjamin", "Blake", "Bobby", "Bradley", "Brandon", 
    "Callum", "Calvin", "Cameron", "Charles", "Charlie", "Chester", "Christian", "Christopher", "Cian", "Connor", 
    "Dallas", "Damien", "Damon", "Daniel", "Darby", "Darrel", "Darren", "Darvin", "Darwin", "David", "Dean", "Delaney", "Delbert", "Dennis", "Denzel", "Derek", "Desmond", "Devin", "Devon", "Dexter", "Dirk", "Dominic", "Donald", "Donovan", "Dorian", "Douglas", "Drake", "Duke", "Duncan", "Dustin", "Dwayne", "Dwight", "Dylan", 
    "Edward", "Eli", "Elijah", "Elliot", "Elliott", "Ellis", "Ethan", "Ewan", 
    "Felix", "Finlay", "Finley", "Finn", "Francis", "Freddie", "Frederick", 
    "Gabriel", "Gavin", "Gene", "Geoffrey", "George", "Gerald", "Gerry", "Giles", "Giovanni", "Glen", "Godfrey", "Gordon", "Graham", "Grant", "Grayson", "Gregory", "Gulliver", "Gunnar", "Gus", "Guy",
    "Hamish", "Harley", "Harrison", "Harry", "Harvey", "Henry", "Hugo", "Hunter", 
    "Ian", "Iggy", "Ike", "Isaac", "Isaiah", "Ivor",
    "Jack", "Jacob", "Jake", "James", "Jamie", "Jasper", "Jayden", "Jenson", "Joel", "John", "Jonathan", "Joseph", "Joshua", "Jude", 
    "Kade", "Kaden", "Kai", "Kaleb", "Kane", "Karl", "Keith", "Kelvin", "Kenneth", "Kent", "Kermit", "Kevin", "Kian", "Kirk", "Kurt", "Kyle", 
    "Laurence", "Leo", "Leon", "Leonard", "Lewis", "Liam", "Logan", "Louis", "Lucas", "Luke", 
    "Malcolm", "Marcus", "Mason", "Matthew", "Max", "Michael", "Milo", 
    "Nathan", "Nicholas"
];
const namesBritishSurnames = [
    "Adams", "Agar", "Allen", "Anderson", "Angel", "Armstrong", "Atkinson", "Austen",
    "Bacon", "Bailey", "Baker", "Barker", "Barnes", "Batten", "Bell", "Bennett", "Black", "Blake", "Booth", "Bond", "Bowling", "Bradford", "Bradley", "Brett", "Bronte", "Brown", "Bristol", "Bryant", "Burton", "Butler", "Byron",
    "Campbell", "Carr", "Carrington", "Carroll", "Carter", "Chapman", "Chaucer", "Christie", "Clark", "Clarke", "Collins", "Constable", "Cook", "Cooper", "Cox", "Crawford", "Croft", "Cunningham", 
    "Dahl", "Davies", "Davis", "Dawson", "Day", "Defoe", "Derby", "Dickens", "Dixon", "Douglas", "Duncan", 
    "Earby", "Earl", "Easing", "Eastwood", "Eccles", "Edenbridge", "Edmonton", "Edwards", "Elliott", "Ellis", "Emin", "Enfield", "Epping", "Epsom", "Erith", "Elton", "Eye", "Evans", "Everett",
    "Fairford", "Fakenham", "Farnborough", "Farnham", "Fazeley", "Featherstone", "Fenton", "Ferndown", "Ferryhill", "Filton", "Finch", "Fisher",  "Fleet", "Fleetwood", "Fleming", "Fletcher", "Flitwick", "Follett", "Ford", "Foster", "Fox", "Fraser", "Frodishman", "Frome", "Frost",
    "Gainsborough", "Garstang", "Gateshead", "Gibson", "Gillingham", "Glastonbury", "Glossop", "Goole", "Graham", "Granger", "Grant", "Gray", "Green", "Griffiths", "Grimsby", "Guilford", "Guisborough",
    "Hadid", "Haggard", "Haig", "Hall", "Hamilton", "Harris", "Harrison", "Hart", "Harvey", "Hawkins", "Hayes", "Hemming", "Henderson", "Hepburn", "Hepworth", "Hill", "Hirst", "Hockney", "Holmes", "Hopkins", "Howard", "Hudson", "Hughes", "Hunt", "Hunter", 
    "Jackson", "James", "Jarrow", "Jenkins", "Johnson", "Johnston", "Jones", 
    "Kelly", "Kempston", "Kendal", "Kenilworth", "Kennedy", "Kesgrave", "Keswick", "Kettering", "Keynes", "Khan", "King", "Kingston", "Kirby", "Kirkham", "Knutt", "Knight", 
    "Lane", "Lawrence", "Lawson", "Lee", "Lessing", "Lewis", "Lloyd", "London", "Lowry",
    "Maiden", "Marshall", "Martin", "Mason", "Matthews", "McEwan", "McDonald", "Merriman", "Mills", "Miller", "Mitchell", "Moore", "Morgan", "Morris", "Mortimer", "Murphy", "Murray", 
    "Nailsworth", "Needham", "Nelson", "Neston", "Newbury", "Newent", "Newport", "Newton", "North", "Northham", "Norton", "Nunn",
    "Oakgate", "Oakham", "Oldbury", "Ongar", "Orwell", "Otley", "Overton", "Oxford",
    "Paddock", "Patchway", "Pateley", "Penistone", "Pershore", "Peters", "Pickering", "Polegate", "Poole", "Portland", "Potter", "Potton", "Prince", "Pudsey", "Pullman", "Purley",
    "Queens", "Queensgate",
    "Radstock", "Raleigh", "Ramsey", "Reading", "Redcar", "Redhill", "Reynolds", "Ringwood", "Ripley", "Roberts", "Rochdale", "Rochester", "Romford", "Romsey", "Ronald", "Rothwell", "Rowley", "Rowling", "Royston", "Rugby", "Runcorn", "Rushden", "Ryde", "Rye",
    "Sale", "Saltash", "Saltburn", "Sandhurst", "Sandown", "Sandwich", "Sandy", "Selby", "Shakespeare", "Shank", "Shefford", "Shelley", "Shepton", "Sheringham", "Shields", "Shildon", "Shipton", "Shirebrook", "Sidmouth", "Sitting", "Skipton", "Smethwick", "South", "Spalding", "Stafford", "Stanley", "Stock", "Stockport", "Stone", "Stonehouse", "Stubbs", "Swift",
    "Tadcaster", "Tadley", "Tamworth", "Taunton", "Telford", "Tenbury", "Thame", "Thatcher", "Thirsk", "Thompson", "Thorn", "Thorpe", "Tickhill", "Trollope", "Truman", "Turner",
    "Wateridge", "Wells", "Whale", "White", "Whitman", "Woods", "Woolf", "Wordsworth", "Wynne", 
    "York"
]

const oddNames = [
    "adder", "ample", "angle", "apple", "april", "arrow", "art", "autumn",
    "bad", "bag", "bake", "barn", "beak", "beaker", "beat", "bellow", "bend", "big", "bird", "bite", "bitter", "black", "blank", "blink", "blood", "bloom", "blot", "blunt", "blush", "body", "bone", "boost", "bomb", "bottle", "bottom", "bow", "brace", "breast", "bright", "brim", "bronze", "brow", "buckle", "bug", "bung", "bulb",
    "candle", "cheer", "chin", "choke", "clean", "clever", "clock", "coal", "cobble", "cockle", "coin", "collar", "conker", "cook", "crab", "crack", "crawl", "crease", "creep", "crescent", "crest", "cross", "curve", 
    "dance", "dandy", "dare", "dark", "dash", "deep", "dew", "dim", "dog", "drape", "dread", "dream", "drift", "drop", "dry", "dust",
    "eager", "early", "easy", "egg", "elbow", "elf", "ember", "end", "envy",
    "face", "fang", "far", "farm", "father", "feather", "fever", "finger", "flake", "flannel", "fleck", "fool", "foot", "forge", "fossil", "fright", "frock", "fun", "funk", "funnel", "fur",
    "gallop", "gallow", "gamble", "gap", "gay", "gaze", "glove", "gold", "good", "grab", "grain", "grass", "gray", "great", "gull", "gum", "gut",
    "hair", "hall", "hand", "harm", "harp", "harsh", "hat", "haunt", "hay", "head", "health", "heap", "heart", "heir", "herb", "hill", "hinder", "hint", "hit", "hold", "honey", "honor", "host", "hot", "hound", "hurry", "hush",
    "idol", "imp", "iron", 
    "jangle", "jiggle", "joint", "judge", "jug", "juice",
    "karma", "keep", "keg", "kennel", "kettle", "key", "kick", "kid", "kidney", "kind", "king", "knuckle",
    "lady", "lamp", "large", "lash", "lay", "leather", "leg", "lemon", "lever", "lime", "lip", "lock", "lode", "long", "love", "loyal", "lung",
    "man", "march", "mask", "meal", "meat", "mellow", "might", "minute", "moist", "mold", "monk", "mop", "motor", "muscle", "mush",
    "nail", "nap", "near", "neat", "neck", "nest", "nettle", "new", "night", "nip", "noon", "nose", "nut",
    "old", "olive", "omen", "organ", "oval",
    "paper", "parch", "patch", "pay", "peach", "pedal", "peel", "pick", "pin", "pint", "play", "pluck", "plumb", "pocket", "polish", "pond", "pop", "pouch", "prawn", "press", "pretty", "pringle", "pull", "punt", "pure",
    "quarrel", "quench", "quiver",
    "rail", "rain", "ram", "reach", "roll", "rope", "round", "rib", "ridge", "ring", "rinse", "ripple", "rose", "rub", 
    "sack", "salad", "search", "season", "seat", "scallop", "score", "shackle", "shake", "sharp", "shed", "shudder", "shut", "sick", "side", "silver", "sin", "skip", "slam", "sleep", "slope", "slow", "slumber", "smootch", "smooth", "snore", "snort", "socket", "soft", "sound", "spine", "splinter", "split", "spring", "sprout", "squash", "star", "starch", "steal", "steam", "steel", "stew", "stiff", "stitch", "stone", "stool", "strange", "strangle", "strap", "strike", "strum", "study", "suckle", "suffer", "sun", "sweep", "sweet",
    "tall", "table", "tail", "tea", "temper", "tank", "tart", "tender", "tent", "thread", "throb", "thrush", "thumb", "tick", "tight", "time", "tint", "toad", "tongue", "tool", "top", "tough", "tower", "track", "trample", "tread", "treat", "trump", "twitch", 
    "usher", "utter",
    "veil", "vile", "vine", 
    "wand", "waft", "war", "warm", "wart", "waste", "wave", "way", "wear", "weasle", "weather", "weep", "weight", "west", "whale", "whimper", "whip", "whistle", "white", "wick", "wind", "wine", "winter", "wipe", "wise", "wish", "witch", "wolf", "wonder", "work", "worn", "wrack", "wreck",
];

const fashion_styles = [
    "Casual - Comfortable, Practical",
    "Elegant - Timeless, Glamour, Regal, Tasteful",
    "Formal - Polished, Professional, Tailored",
    "Bohemian - Free-Spirited, Artistic, Flowing",
    "Streetwear - Urban, Oversized, Self-Expressive",
    "Minimalist - Simplicity, Clean-Lines",
    "Preppy - Academic, Neutral-Colors, Classic-Patterns",
    "Girly - Flirty, Ruffles, Lace, Pastels, Florals, Ballet",
    "Edgy - Leather, Distressed Denim, Graphic Tees, Studs, Chunky Gear",
    "Retro - High-Waisted Skirts, A-Line Dresses, Retro Accessories",
    "Vintage - Era-Specific",
    "Sporty - Hoodies, Sweatpants, Gymwear, Athletic Brands, Caps, Gym Bags",
    "Country - Durable Denim, Plaid, Work Boots, Overalls, Leather, Wide-Brimmed Hats",
    "Romantic - Flowing, Floral, Delicate, Lace, Silk, Intricate Embroidery",
    "Sexy - Form-Fitting, Figure-Hugging, Low Cuts, Crop Tops, Sheer Fabric, Statement Heels",
    "Military - Camoflage, Cargo Pants, Boots, Trench Coats, Bomber Jackets, Sunglasses",
    "Prep 2000 - Wealth, Popularity, Femininity, Elitism, Light & Bright colors",
    "Eclectic - Oversized Topcoats, Cardigans, High-Waisted Trousers, Sensible Footware, Neutral Tones, Earthy Colors",
    "Emo - Side-Swept Bangs, Skinny Jeans, Band T-Shirt, Studded Belts, Converse Sneakers, Heavy Eyeliner, Primarily Black with Colored Accents.",
    "Ethnic Chic - Global Textures, Handcrafted, Natural Materials, Cultural Patterns, Warm Earth Tones",
    "Punk - Non-Conformist, DIY Aesthetics, Shock-wear",
    "Romantic Goth - Flowing, Velvet, Lace, Corsetry, Black, Deep Jewel tones",
    "Tennis-Core - Tennis Skirts, Shirts, Shoes & Socks, Visors, Sweatbands, White, Green, Navy",
    "Decora - Excessive Layering of Accessories, Stickers, Bright Primary Colors, Rainbow Palette",
    "Mori Kei - Forests & Fairytales, Flowers & Flowing Nightgowns, White, Earthtones"
];

const cozyActivity = [
    "Antiques, Vintage, Retro, Furniture, Fashions",
    "Cooking, Baking, Catering, Hosting",
    "Nature Twitching",
    "Charity, Community",
    "Food & Drink, Dining, Tasting, Night Clubbing",
    "Gardening, Planting, Harvesting",
    "Needlework, Knitting, Embroidery, Quilting",
    "Art, Painting, Drawing, Sculpture, Pottery",
    "Scrapbooking, Documenting, Archiving",
    "Collecting (Stamps, Shells, Coins, Flowers, ...)",
    "Sport, Exercise, Athletics, Acrobatics",
    "Games, Puzzles, Cards, Roleplaying",
    "Shooting, Archery, Darts, Bowling",
    "Computers, Programming, Hacking",
    "Animals, Petting Zoos, Safari, Farmyard",
    "Education, Reading, Research"
];