const tricubeCardOracle = [
    "Joker of Clubs: Unexpected Scene change!",
    "Joker of Spades: Unexpected Scene change!",
    "Joker of Diamonds: Unexpected Scene change!",
    "Joker of Hearts: Unexpected Scene change!",
    "Ace of Clubs: Unexpected Scene change!",
    "Ace of Spades: Unexpected Scene change!",
    "Ace of Diamonds: Unexpected Scene change!",
    "Ace of Hearts: Unexpected Scene change!",
    "King of Clubs: Advance Main Plot (Negative). Interpret the result. Draw again.",
    "King of Spades: Advance Main Plot (Negative). Interpret the result. Draw again.",
    "King of Diamonds: Advance Main Plot (Positive). Interpret the result. Draw again.",
    "King of Hearts: Advance Main Plot (Positive). Interpret the result. Draw again.",
    "Queen of Clubs: Advance Primary Sub-Plot (Negative). Interpret the result. Draw again.",
    "Queen of Spades: Advance Primary Sub-Plot (Negative). Interpret the result. Draw again.",
    "Queen of Diamonds: Advance Primary Sub-Plot (Positive). Interpret the result. Draw again.",
    "Queen of Diamonds: Advance Primary Sub-Plot (Positive). Interpret the result. Draw again.",
    "Jack of Clubs: Advance Primary Secondary Sub-Plot (Negative). Interpret the result. Draw again.",
    "Jack of Spades: Advance Primary Secondary Sub-Plot (Negative). Interpret the result. Draw again.",
    "Jack of Diamonds: Advance Primary Secondary Sub-Plot (Positive). Interpret the result. Draw again.",
    "Jack of Hearts: Advance Primary Secondary Sub-Plot (Positive). Interpret the result. Draw again.",
    "10 of Clubs: Hard Crafty Challenge. Roll 6 to win the scene.",
    "10 of Spades: Hard Crafty Challenge. Roll 6 to win the scene.",
    "10 of Diamonds: Hard Crafty Challenge. Roll 6 to win the scene.",
    "10 of Hearts: Hard Crafty Challenge. Roll 6 to win the scene.",
    "9 of Clubs: Standard Crafty Challenge. Roll 5 or 6 to win the scene.",
    "9 of Spades: Standard Crafty Challenge. Roll 5 or 6 to win the scene.",
    "9 of Diamonds: Standard Crafty Challenge. Roll 5 or 6 to win the scene.",
    "9 of Hearts: Standard Crafty Challenge. Roll 5 or 6 to win the scene.",
    "8 of Clubs: Easy Crafty Challenge. Roll 4, 5 or 6 to win the scene.",
    "8 of Spades: Easy Crafty Challenge. Roll 4, 5 or 6 to win the scene.",
    "8 of Diamonds: Easy Crafty Challenge. Roll 4, 5 or 6 to win the scene.",
    "8 of Hearts: Easy Crafty Challenge. Roll 4, 5 or 6 to win the scene.",
    "7 of Clubs: Hard Brawny Challenge. Roll 6 to win the scene.",
    "7 of Spades: Hard Brawny Challenge. Roll 6 to win the scene.",
    "7 of Diamonds: Hard Brawny Challenge. Roll 6 to win the scene.",
    "7 of Hearts: Hard Brawny Challenge. Roll 6 to win the scene.",
    "6 of Clubs: Standard Brawny Challenge. Roll 5 or 6 to win the scene.",
    "6 of Spades: Standard Brawny Challenge. Roll 5 or 6 to win the scene.",
    "6 of Diamonds: Standard Brawny Challenge. Roll 5 or 6 to win the scene.",
    "6 of Hearts: Standard Brawny Challenge. Roll 5 or 6 to win the scene.",
    "5 of Clubs: Easy Brawny Challenge. Roll 4, 5 or 6 to win the scene.",
    "5 of Spades: Easy Brawny Challenge. Roll 4, 5 or 6 to win the scene.",
    "5 of Diamonds: Easy Brawny Challenge. Roll 4, 5 or 6 to win the scene.",
    "5 of Hearts: Easy Brawny Challenge. Roll 4, 5 or 6 to win the scene.",
    "4 of Clubs: Hard Agile Challenge. Roll 6 to win the scene.",
    "4 of Spades: Hard Agile Challenge. Roll 6 to win the scene.",
    "4 of Diamonds: Hard Agile Challenge. Roll 6 to win the scene.",
    "4 of Hearts: Hard Agile Challenge. Roll 6 to win the scene.",
    "3 of Clubs: Standard Agile Challenge. Roll 5 or 6 to win the scene.",
    "3 of Spades: Standard Agile Challenge. Roll 5 or 6 to win the scene.",
    "3 of Diamonds: Standard Agile Challenge. Roll 5 or 6 to win the scene.",
    "3 of Hearts: Standard Agile Challenge. Roll 5 or 6 to win the scene.",
    "2 of Clubs: Easy Agile Challenge. Roll 4, 5 or 6 to win the scene.",
    "2 of Spades: Easy Agile Challenge. Roll 4, 5 or 6 to win the scene.",
    "2 of Diamonds: Easy Agile Challenge. Roll 4, 5 or 6 to win the scene.",
    "2 of Hearts: Easy Agile Challenge. Roll 4, 5 or 6 to win the scene.",
]

// Scene Change Table
const tricubeSceneChange = [
    "Positive for you. Interpret the result. Draw again.",
    "Negative for you. Interpret the result. Draw again.",
    "Roll on a <i>Twist Table</i>. Interpret the result. Draw again.",
    "Create, choose, or roll a <b>NEW LOCATION</b>. Interpret the result. Draw again.",
    "Create, choose, or roll a <b>NEW PERSON</b>. Interpret the result. Draw again.",
    "Create, choose, or roll a <b>NEW EVENT</b>. Interpret the result. Draw again."
]