const magicalWeaponsAndArmor = [
    {roll: 1, type: "Cursed Armor or Shield"},
    {roll: 2, type: "+1 Missile Weapon"},
    {roll: 3, type: ""},
    {roll: 4, type: ""},
    {roll: 5, type: ""},
    {roll: 6, type: ""},
    {roll: 7, type: ""},
    {roll: 8, type: ""},
    {roll: 9, type: ""},
    {roll: 10, type: ""},
    {roll: 11, type: ""},
    {roll: 12, type: ""},
    {roll: 13, type: ""},
    {roll: 14, type: ""},
    {roll: 15, type: ""},
    {roll: 16, type: ""},
    {roll: 17, type: ""},
    {roll: 18, type: ""},
    {roll: 19, type: ""},
    {roll: 20, type: ""},
];